"use client"

import { useState } from "react"
import Link from "next/link"
import { PawPrint, Loader2 } from "lucide-react"
import { createClient } from "@/lib/supabase/client"
import { Button } from "@/components/ui/button"

export default function SignupPage() {
  const supabase = createClient()
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState("")
  const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [loading, setLoading] = useState(false)
  async function submit(e: React.FormEvent) { e.preventDefault(); setError(null); setMessage(null); if(password.length<6){setError("Password must be at least 6 characters.");return} if(password!==confirm){setError("Passwords do not match.");return} setLoading(true); const { data, error }=await supabase.auth.signUp({email:email.trim(),password,options:{emailRedirectTo:`${window.location.origin}/auth/callback`}}); if(error){setError(error.message);setLoading(false);return} if(data.session) window.location.href="/"; else {setMessage("Account created. Check your email to confirm your account, then log in.");setLoading(false)} }
  return <main className="flex min-h-dvh items-center justify-center bg-background p-6"><div className="w-full max-w-md rounded-3xl border border-border bg-card p-7 shadow-xl"><div className="mb-7 text-center"><div className="mx-auto mb-3 flex size-12 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><PawPrint /></div><h1 className="font-serif text-2xl font-extrabold">Create your PawFinder account</h1><p className="mt-1 text-sm text-muted-foreground">Post reports and receive important updates.</p></div><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-semibold">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3 outline-none focus:ring-3 focus:ring-ring/30" /></label><label className="block text-sm font-semibold">Password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3 outline-none focus:ring-3 focus:ring-ring/30" /></label><label className="block text-sm font-semibold">Confirm password<input required type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3 outline-none focus:ring-3 focus:ring-ring/30" /></label>{error&&<p className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{message&&<p className="rounded-xl bg-primary/10 p-3 text-sm text-foreground">{message}</p>}<Button className="w-full" size="lg" disabled={loading}>{loading?<><Loader2 className="animate-spin"/> Creating…</>:"Create account"}</Button></form><p className="mt-5 text-center text-sm text-muted-foreground">Already have an account? <Link className="font-bold text-primary hover:underline" href="/auth/login">Log in</Link></p><p className="mt-3 text-center"><Link className="text-sm text-muted-foreground hover:underline" href="/">← Back to map</Link></p></div></main>
}
