export const metadata = { title: "Privacy Notice | Pet Alert PH" }
export default function PrivacyPage(){return <main className="mx-auto max-w-3xl px-5 py-10 text-sm leading-7"><h1 className="font-serif text-3xl font-extrabold">Pet Alert PH Privacy Notice</h1><p className="mt-2 text-muted-foreground">Last updated: July 27, 2026</p><section className="mt-8 space-y-5">
<p>This notice describes how Pet Alert PH processes account details, reports, sightings, map coordinates, contact information, chats, notifications, uploaded photos, and basic technical/security records.</p>
<h2 className="text-xl font-bold">Purposes</h2><p>We process information to create accounts, publish reports and sightings, coordinate volunteers, deliver notifications and private chats, prevent abuse, maintain security, respond to requests, and comply with legal obligations.</p>
<h2 className="text-xl font-bold">Public and private data</h2><p>Report and sighting content may be publicly visible. Private chats and account notifications are limited to authorized users through database access controls. Do not submit unnecessary sensitive personal information.</p>
<h2 className="text-xl font-bold">Service providers</h2><p>Pet Alert PH currently relies on Supabase for authentication, database, realtime, and file storage; Vercel for hosting; and map-tile providers for map display. These providers may process technical information needed to deliver their services.</p>
<h2 className="text-xl font-bold">Retention</h2><p>Active reports and relevant activity are retained while needed for the service. Read notifications may be removed after 90 days. Closed-case chat text may be removed after one year. Deleted or expired image files are queued for removal. Backups and security logs may persist for limited additional periods.</p>
<h2 className="text-xl font-bold">Your choices and rights</h2><p>You may delete your own report or sighting in the app. You may also request access, correction, objection, erasure or blocking, and other rights available under applicable Philippine data-protection law. Requests may require identity verification.</p>
<h2 className="text-xl font-bold">Security</h2><p>We use authentication, row-level database policies, restricted chats, and account-based permissions. No internet system is completely risk-free, so users should avoid posting unnecessary personal or sensitive data.</p>
<h2 className="text-xl font-bold">Contact</h2><p>Pet Alert PH is operated by Nicholas Quintela. For support, privacy requests, access, correction, or deletion requests, email <strong>quintelanicholas3@gmail.com</strong>.</p>
</section></main>}
