export const metadata = { title: "Terms of Use | Pet Alert PH" }
export default function TermsPage(){return <main className="mx-auto max-w-3xl px-5 py-10 text-sm leading-7"><h1 className="font-serif text-3xl font-extrabold">Pet Alert PH Terms of Use</h1><p className="mt-2 text-muted-foreground">Last updated: July 27, 2026</p>
<section className="mt-8 space-y-5">
<p><strong>Important:</strong> Pet Alert PH is a community information and coordination platform. It is not an emergency service, law-enforcement service, veterinary service, animal shelter, escrow service, or guarantee that an animal will be recovered. For emergencies, danger, cruelty, theft, or suspected crime, contact the appropriate local authority, barangay, police, veterinarian, shelter, or animal-welfare organization.</p>
<h2 className="text-xl font-bold">1. Eligibility and accounts</h2><p>You must provide accurate account information, protect your login credentials, and be responsible for activity performed through your account. Do not impersonate another person.</p>
<h2 className="text-xl font-bold">2. User content and permissions</h2><p>You remain responsible for reports, sightings, photos, messages, locations, contact details, and other content you submit. You confirm that your content is accurate to the best of your knowledge, lawful, and that you have permission to upload and share it. You grant Pet Alert PH a non-exclusive permission to host, display, process, and share that content only as needed to operate and improve the service.</p>
<h2 className="text-xl font-bold">3. Public location and contact information</h2><p>Lost-pet reports and sightings may expose approximate locations, images, and contact information to the public. Do not post a private home address, government ID, financial information, passwords, medical data, or information about children. Use an approximate public location where practical.</p>
<h2 className="text-xl font-bold">4. Prohibited conduct</h2><p>Do not post false reports, demand money dishonestly, harass users, stalk people, arrange unsafe meetings, publish another person’s private data without authority, upload unlawful or harmful material, interfere with the service, or use Pet Alert PH to facilitate theft, fraud, animal abuse, or any illegal activity.</p>
<h2 className="text-xl font-bold">5. Volunteers, chats, rewards, and meetings</h2><p>Users communicate and meet at their own judgment and risk. Verify information, meet in safe public places, bring another trusted person when appropriate, and do not send money or reveal sensitive information merely because another user claims to have found an animal. Pet Alert PH does not verify every user, sighting, reward, message, or recovery claim and is not a party to private arrangements.</p>
<h2 className="text-xl font-bold">6. Moderation and removal</h2><p>Pet Alert PH may restrict, hide, preserve, or remove accounts and content that appear unsafe, unlawful, misleading, abusive, technically harmful, or inconsistent with these Terms. Users may delete their own reports and sightings, subject to limited retention needed for security, legal compliance, dispute handling, and backup cycles.</p>
<h2 className="text-xl font-bold">7. Availability and no guarantee</h2><p>The service is provided on an “as available” basis. Maps, locations, notifications, chats, links, and third-party services may be delayed, inaccurate, unavailable, or interrupted. Pet Alert PH does not promise successful recovery, continuous operation, identity verification, or the accuracy of user-generated content.</p>
<h2 className="text-xl font-bold">8. Responsibility and limitation</h2><p>To the maximum extent permitted by applicable law, users remain responsible for their decisions, communications, meetings, uploaded content, and compliance with law. Nothing in these Terms excludes liability that cannot legally be excluded, including liability arising from fraud, willful misconduct, gross negligence where applicable, or rights granted by mandatory law.</p>
<h2 className="text-xl font-bold">9. Privacy</h2><p>Our Privacy Notice explains what information is collected, why it is processed, how long it may be retained, and available data-subject rights.</p>
<h2 className="text-xl font-bold">10. Changes and governing law</h2><p>These Terms may be updated when the service changes. Continued use after notice means acceptance of the revised Terms. These Terms are governed by applicable laws of the Republic of the Philippines, without limiting mandatory rights that apply to a user.</p>
<h2 className="text-xl font-bold">11. Contact</h2><p>Support and privacy contact: Nicholas Quintela — <strong>quintelanicholas3@gmail.com</strong>.</p>
</section></main>}
